DjangoChickSim/urls.py
from django.conf.urls.static import static
from django.conf import settings

from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('core.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('buildings/', include('buildings.urls')),
    path('market/', include('market.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

buildings/urls.py
from django.urls import path

from . import views

app_name = 'buildings'

urlpatterns = [
    path('', views.index, name='index'),
    path('build_building/', views.build_building, name='build_building'),
    path('upgrade/', views.upgrade_building, name='upgrade_building'),
    path('save_eggs/', views.save_eggs, name='save_eggs'),
    path('collect_eggs/', views.collect_eggs, name='collect_eggs'),
]

core/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path

from .forms import LoginForm
from . import views


app_name = 'core'

urlpatterns = [
    path('', views.index, name='index'),
    path('signup/', views.signup, name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name='core/login.html', authentication_form=LoginForm), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('soon/', views.soon, name='soon'),
    path('live_data/', views.live_data, name='live_data'),
]

buildings/models.py
from django.db import models
from celery import shared_task
from datetime import timedelta
from django.utils import timezone

class Building(models.Model):
    
    id = models.IntegerField(primary_key=True)
    
    name = models.CharField(max_length=50)
    description = models.TextField()
    level = models.IntegerField(default=1)
    
    cost = models.FloatField(default=0)

    eggs_per_click = models.FloatField(default=0)
    
    egg_capacity = models.IntegerField(default=0)
    
    owned = models.BooleanField(default=False)

    def __str__(self):
        return self.name

buildings/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from buildings.models import Building
from user.models import UserProfile, BuildingLevel
from django.contrib import messages
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt


@login_required
def index(request):
    user_profile = UserProfile.objects.get(user=request.user)
    buildings = Building.objects.all()
    building_levels = BuildingLevel.objects.filter(user_profile=user_profile)
    building_levels_dict = {bl.building_id: bl.level for bl in building_levels}
    building_eggs_dict = {bl.building_id: bl.egg_in_storage for bl in building_levels}


    
    context = {
        'user_profile': user_profile,
        'buildings': buildings,
        'building_levels': building_levels_dict,
        'building_eggs': building_eggs_dict,
    }
    return render(request, 'buildings/index.html', context)


@login_required
def upgrade_building(request):
    if request.method == 'POST':
        building_id = request.POST.get('building_id')
        user_profile = UserProfile.objects.get(user=request.user)
        building_level = BuildingLevel.objects.get(user_profile=user_profile, building_id=building_id)
        building = building_level.building
        building_upgrade_cost = (building_level.level+building.cost)*180
        if user_profile.money >= building_upgrade_cost:
            user_profile.money -= building_upgrade_cost
            building_level.level += 1
            building_level.save()
            user_profile.save()
            messages.success(request, f'{building.name} upgraded to level {building_level.level}')
        else:
            messages.error(request, f'Not enough money to upgrade {building.name}')
    return redirect('buildings:index')


@login_required
def build_building(request):  
    if request.method == 'POST':
        building_id = request.POST.get('building_id')
        building = Building.objects.get(id=building_id)
        user_profile = request.user.userprofile
        if user_profile.money >= building.cost:
            user_profile.money -= building.cost
            user_profile.buildings.add(building)
            building.owned = True
            building.save()
            user_profile.save()            
            messages.success(request, f'{building.name} built successfully')
        else:
            messages.error(request, f'Not enough money to build {building.name}')
        return redirect('buildings:index')
    else:
        return redirect('buildings:index')
    
    
@login_required
@csrf_exempt  # Remove if you're handling CSRF tokens differently
def save_eggs(request):
    if request.method == 'POST':
        try:
            import json
            data = json.loads(request.body.decode('utf-8'))
            id = data.get('id')
            content = data.get('content')

            # Process the data as needed (e.g., save it to the database)

            user_profile = UserProfile.objects.get(user=request.user)
            building_levels = BuildingLevel.objects.filter(user_profile=user_profile)
            building_eggs_dict = {bl.building_id: bl.egg_in_storage for bl in building_levels}
            
            building_eggs_dict.update({int(id): float(content)})
            #Now save this new data
            for building_id, egg_count in building_eggs_dict.items():
                building_level = BuildingLevel.objects.get(user_profile=user_profile, building_id=building_id)
                building_level.egg_in_storage = egg_count
                building_level.save()
            

            return JsonResponse({'message': 'Data received and processed successfully'})
        except json.JSONDecodeError:
            return JsonResponse({'error': 'Invalid JSON data'}, status=400)

    return JsonResponse({'error': 'Invalid request method'}, status=400)


@login_required
def collect_eggs(request):
    if request.method == 'POST':
        user_profile = UserProfile.objects.get(user=request.user)
        building_levels = BuildingLevel.objects.filter(user_profile=user_profile)
        building_eggs_dict = {bl.building_id: bl.egg_in_storage for bl in building_levels}
        id = request.POST.get('building_id')
        building = Building.objects.get(id=id)
        egg_count = building_eggs_dict.get(int(id))
        user_profile.update_int_array(egg_count)
        user_profile.Egg += egg_count
        building_eggs_dict.update({int(id): 0})
        #now save this new data
        building_level = BuildingLevel.objects.get(user_profile=user_profile, building_id=id) 
        building_level.egg_in_storage = 0
        building_level.save()
        user_profile.save()
   
        messages.success(request, f'Collected {egg_count} eggs')
    return redirect('buildings:index')

buildings/templates/buildings/index.html
{% extends 'core/base.html' %}

{% load custom_filters %}

{% block content %}
{% for msg in messages %}
{% if msg.tags == 'error' %}
<div class="px-6 py-4 mb-4 text-sm text-center bg-red-500 rounded-xl opacity-50 text-white-100 text-4xl font-bold">
    {{ msg }}
</div>
{% endif %}
{% if msg.tags == 'success' %}
<div class="px-6 py-4 mb-4 text-sm text-center bg-green-500 rounded-xl opacity-50 text-white-100 text-4xl font-bold">
    {{ msg }}
</div>
{% endif %}
{% endfor %}
<div class="mt-6 mb-6 px-6 py-12 bg-gray-100 rounded-xl">
    <h1 class="mb-6 text-4xl font-bold text-center text-sky-950">Buildings</h1>
    <div class="flex flex-col items-center justify-center">
        <div class="grid grid-cols-3 gap-4">
            {% for building in buildings %}
            <div class="flex flex-col items-center justify-center p-4 bg-white rounded-xl shadow-md">
                <h1 class="mb-2 text-2xl font-bold text-center text-sky-950">{{ building.name }}</h1>
                <p class="mb-2 text-center text-sky-950">{{ building.description }}</p>
                {% if building in user_profile.buildings.all %}
                <p class="mb-2 text-center text-sky-950">Level: {{ building_levels|get:building.id }}</p>
                {% else %}
                <p class="mb-2 text-center text-sky-950">{{ building.cost }}$</p>
                {% endif %}
                {% if building in user_profile.buildings.all %}
                <a class="mb-2 text-center text-sky-950" href="#">Eggs per click : <span id="{{building.id}}eggs_per_click">{{ building_levels|get:building.id|add:building.eggs_per_click|pow:3|mul:0.1|round }}</span></a>
                <a class="mb-2 text-center text-sky-950" href="#">Eggs in storage : <span id="{{building.id}}egg">{{ building_eggs|get:building.id }}</span> / <span id="{{building.id}}egg_limit">{{ building_levels|get:building.id|add:building.egg_capacity|mul:1|pow:3 }}</span> </a>

                
                <p>Upgrade cost: {{ building_levels|get:building.id|add:building.cost|pow:3}}$</p>
                <form method="post" action="{% url 'buildings:upgrade_building' %}">
                    {% csrf_token %}
                    <input type="hidden" name="building_id" value="{{ building.id }}">
                    <button type="submit" class="px-4 mt-4 py-2 text-white bg-sky-950 rounded-xl hover:bg-sky-800">Upgrade</button>
                </form>
                <button class="px-4 py-2 mt-4 text-white bg-sky-800 rounded-xl hover:bg-sky-700" onclick="add_egg_to_storage('{{ building.id }}egg', '{{ building.id }}egg_limit', '{{ building.id }}eggs_per_click')">Add to storage</button>
                <form method="post" action="{% url 'buildings:collect_eggs' %}">
                    {% csrf_token %}
                    <input type="hidden" name="building_id" value="{{ building.id }}">
                <button type="submit" class="px-4 py-2 mt-4 text-white bg-red-950 rounded-xl hover:bg-red-800">Collect eggs</button>
                </form>
                {% else %}
                <form method="post" action="{% url 'buildings:build_building' %}">
                    {% csrf_token %}
                    <input type="hidden" name="building_id" value="{{ building.id }}">
                    <button type="submit" class="px-4 py-2 text-white bg-sky-950 rounded-xl hover:bg-sky-800">Build</button>
                </form>
            {% endif %}
            </div>
            {% endfor %}
        </div>
    </div>
</div>
<script>

    let all_egg_elements_id_dict = {};

    const add_egg_to_storage = (eggs_storage, egg_limit, eggs_per_click) => {
        let egg = document.getElementById(eggs_storage);
        let egg_limit_element = document.getElementById(egg_limit);
        let eggs_per_click_element = document.getElementById(eggs_per_click);
        
        all_egg_elements_id_dict[eggs_storage] = egg;

        if (parseFloat(egg_limit_element.innerHTML) >= parseFloat(egg.innerHTML) + parseFloat(eggs_per_click_element.innerHTML)) {
            egg.innerHTML = (parseFloat(egg.innerHTML) + parseFloat(eggs_per_click_element.innerHTML)).toFixed(1);
        } else {
            egg.innerHTML = egg_limit_element.innerHTML;
            alert('You have reached the limit of your storage');
        }
    }
    
    window.addEventListener('beforeunload', function (e) {
      
        for (const [key, value] of Object.entries(all_egg_elements_id_dict)) {
            let egg = document.getElementById(key);
            id = key.replace('egg', '');
            let data = {
                id: id,
                content: egg.innerHTML
            };
        
            // Send the data to the Django view using Fetch API
            fetch('save_eggs/', {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json',
                    'X-CSRFToken': '{{ csrf_token }}' // Include CSRF token if needed
                },
                body: JSON.stringify(data)
            })
            .then(response => response.json())
            .catch(error => {
                console.error('Error:', error);
            });
        }
    });
    
</script>
{% endblock %}