DjangoChickSim/urls.py
from django.conf.urls.static import static
from django.conf import settings

from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('core.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('buildings/', include('buildings.urls')),
    path('market/', include('market.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path

from .forms import LoginForm
from . import views


app_name = 'core'

urlpatterns = [
    path('', views.index, name='index'),
    path('signup/', views.signup, name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name='core/login.html', authentication_form=LoginForm), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('soon/', views.soon, name='soon'),
    path('live_data/', views.live_data, name='live_data'),
]

dashboard/urls.py
from django.urls import path

from . import views

app_name = 'dashboard'

urlpatterns = [
    path('', views.index, name='index'),
    path('chart_data/', views.chart_data, name='chart_data'),
]

core/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User

class LoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'w-full px-3 py-4 mb-3 text-sm leading-tight text-gray-700 border rounded shadow appearance-none focus:outline-none focus:shadow-outline',
        'placeholder': 'Kajetan.Mieloch2023',
        }))
    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'class': 'w-full px-3 py-4 mb-3 text-sm leading-tight text-gray-700 border rounded shadow appearance-none focus:outline-none focus:shadow-outline',
        'placeholder': 'Password123.',
        }))

class SignupForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')
        
    username = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'w-full px-3 py-4 mb-3 text-sm leading-tight text-gray-700 border rounded shadow appearance-none focus:outline-none focus:shadow-outline',
        'placeholder': 'Kajetan.Mieloch2023',
        }))
    
    email = forms.CharField(widget=forms.EmailInput(attrs={
        'class': 'w-full px-3 py-4 mb-3 text-sm leading-tight text-gray-700 border rounded shadow appearance-none focus:outline-none focus:shadow-outline',
        'placeholder': 'example@example.com',
        }))
    
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={
        'class': 'w-full px-3 py-4 mb-3 text-sm leading-tight text-gray-700 border rounded shadow appearance-none focus:outline-none focus:shadow-outline',
        'placeholder': 'Password123.',
        }))
    
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={
        'class': 'w-full px-3 py-4 mb-3 text-sm leading-tight text-gray-700 border rounded shadow appearance-none focus:outline-none focus:shadow-outline',
        'placeholder': 'Password123.',
        }))

core/views.py
from django.shortcuts import render, redirect
from user.models import UserProfile, BuildingLevel
from buildings.models import Building
from django.http import JsonResponse
from django.contrib.auth.decorators import login_required

from .forms import SignupForm


def index(request):
    return render(request, 'core/index.html')

def signup(request):
    if request.method == 'POST':
        form = SignupForm(request.POST)
        if form.is_valid():
            form.save()
            
            
            user_profile = UserProfile.objects.create(user=form.instance)
            #user_profile.buildings.set(Building.objects.all()[:1])
            user_profile.money = 10
            user_profile.save()
            
            BuildingLevel.objects.bulk_create([
                BuildingLevel(user_profile=user_profile, building=building)
                for building in Building.objects.all()
            ])
                
            return redirect('core:login')
    else:
        form = SignupForm()
    
    return render(request, 'core/signup.html', {
        'form': form,
    })

@login_required
def live_data(request):
    
    user_profile = UserProfile.objects.get(user=request.user)
    
    return JsonResponse({
        'egg': user_profile.Egg,
        'money': user_profile.money,
        'hay': user_profile.Hay,
    })
    
def soon(request):
    return render(request, 'core/soon.html')

core/templates/core/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <script src="https://cdn.tailwindcss.com"></script>

    <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.css"/>
    <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick-theme.css"/>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.min.js"></script>

    <title>{% block title %}{% endblock %}</title>

    <style>{% block style %}{% endblock %}</style>

    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Chart with Tailwind CSS</title>
    <!-- Include Chart.js library -->
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    <!-- Include Tailwind CSS -->
    <link href="https://cdn.jsdelivr.net/npm/tailwindcss@2.2.19/dist/tailwind.min.css" rel="stylesheet">

</head>
<body class="bg-zinc-800">
    <nav class="py-6 px-6 flex justify-between items-center bg-sky-700">
        <div>
            <a href="/" class="text-2xl font-bold text-gray-300">Chick Managment Software</a>
        </div>
        <div class="space-x-6">
            {% if user.is_authenticated %}
                <a class="px-6 py-2 bg-sky-900 text-white rounded hover:bg-sky-800">Hay: <span id="hay-value"></span> </a>
                <a class="px-6 py-2 bg-sky-900 text-white rounded hover:bg-sky-800">Money: <span id="money-value"></span> $</a>
                <a class="px-6 py-2 bg-sky-900 text-white rounded hover:bg-sky-800">Egg: <span id="egg-value"></span> </a>
                <a href="{% url 'dashboard:index' %}" class="px-6 py-2 bg-sky-900 text-white rounded hover:bg-sky-800">Dashboard</a>
                <a href="{% url 'core:logout' %}" class="px-6 py-2 bg-sky-900 text-white rounded hover:bg-sky-800">Logout</a>
            {% else %}
                <a href="{% url 'core:signup' %}" class="px-6 py-2 bg-sky-900 text-white rounded hover:bg-sky-800">Sing up</a>
                <a href="{% url 'core:login' %}" class="px-6 py-2 bg-sky-900 text-white rounded hover:bg-sky-800">Log in</a>
            {% endif %}
        </div>
    </nav>
    <div class="px-6 py-6">
        {% block content %}
        {% endblock %}
    </div>

    <footer class="py-6 px-6 flex justify-between bg-sky-900">
        <div class="w-2/3 pr-10">
            <h3 class="text-gray-200 text-2xl font-bold">Chick Managment Software</h3>
            <p class="text-gray-400">Kajetan Mieloch 2023</p>
        </div>

        <div class="w-1/3">
            <h3 class="mb-5 font-bold text-gray-300">Menu</h3>
            <ul class="text-gray-400">
                <li class="mb-2"><a href="/#" class="hover:text-gray-200">Home Page</a></li>
                <li class="mb-2"><a href="/#" class="hover:text-gray-200">About</a></li>

<script>
    // Initialize variables to store the previous data
    let previousEggValue = null;
    let previousMoneyValue = null;
    let previousHayValue = null;

    function updateLiveData() {
        // Make an AJAX request to fetch live data
        fetch('/live_data/')
            .then(response => response.json())
            .then(data => {
                // Check if the data has changed
                if (data.egg !== previousEggValue) {
                    document.getElementById('egg-value').textContent = data.egg;
                    previousEggValue = data.egg;
                }
                if (data.money !== previousMoneyValue) {
                    document.getElementById('money-value').textContent = data.money;
                    previousMoneyValue = data.money;
                }
                if (data.hay !== previousHayValue) {
                    document.getElementById('hay-value').textContent = data.hay;
                    previousHayValue = data.hay;
                }
            })
    }

    setInterval(updateLiveData, 2000);
</script>

</body>
</html>

core/templates/core/index.html
{% extends "core/base.html" %}

{% block title %}Home{% endblock %}

{% block style %}

.header {
  text-align: center;
  margin-bottom: 20px;
}

.grid {
  display: grid;
  grid-template-columns: repeat(3, 1fr);
  gap: 20px;
  margin-left: 20%;
  width: 60%;
}

.card {
  position: relative;
  max-width: 100%;
  overflow: hidden;
  background-color: #ccc;
  border-radius: 10px;
  box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);
  transition: transform 0.3s ease;
}

.card:hover {
  transform: translateY(-7px);
}

.card img {
  max-width: 100%;
  vertical-align: middle;
}

.card-content {
  padding: 20px;
}

.card-title {
  font-weight: bold;
  font-size: 1.5rem;
  margin-bottom: 10px;
}

.card-description {
  font-size: 1rem;
  color: #333;
}
{% endblock %}


{% block content %}
<h1 class="header text-sky-200 text-5xl font-bold">🐔 Chicken Farming Software</h1>
<p class="header text-sky-200 text-2xl font-bold">The only software you need to manage your chicken farm.</p>
<hr style="width: 60%; margin-left: 20%; margin-top: 20px; margin-bottom: 20px;">
<div class="grid">
  <div class="card">
      <img src="https://i.imgur.com/i40vq4T.jpg" alt="Card 1">
      <div class="card-content">
          <div class="card-title">📈 Make Your Chicks Make You Money!</div>
          <p class="card-description">
              We've cracked the code to turn your feathered friends into financial featherweights. Our cutting-edge software is the 'egg'cellent companion for modern chicken farmers who mean business.
          </p>
      </div>
  </div>
  <div class="card">
      <img src="https://i.imgur.com/2MvJRhC.png" alt="Card 2">
      <div class="card-content">
          <div class="card-title">🐣 Funny Farm, Serious Profits</div>
          <p class="card-description">
              Ready to turn your poultry into profits? Join the 'egg-citing' revolution today and watch your farm 'hatch' success.
          </p>
      </div>
  </div>
  <div class="card">
      <img src="https://i.imgur.com/AfmXfoc.png" alt="Card 3">
      <div class="card-content">
          <div class="card-title">🐓 Chick-Chick, Hooray!</div>
          <p class="card-description">
              Our software is so user-friendly, even your grandpa's favorite rooster could use it. Say goodbye to manual record-keeping and hello to hassle-free hen house management.
          </p>
      </div>
  </div>
</div>
<hr style="width: 60%; margin-left: 20%; margin-top: 20px; margin-bottom: 20px;">
{% if user.is_authenticated %}
  <h1 class="header text-sky-200 text-5xl font-bold">Welcome back {{ user.username }}!</h1>
  <p class="header text-sky-200 text-2xl font-bold">Ready to turn your poultry into profits? Go to dashboard to get started.</p>
{% else %}
  <h1 class="header text-sky-200 text-5xl font-bold">So what are you waiting for?</h1>
  <p class="header text-sky-200 text-2xl font-bold">Join the 'egg-citing' revolution today and watch your farm 'hatch' success.</p>
{% endif %}

<div class="text-center mt-20 mb-20">
  {% if user.is_authenticated %}
    <a href="{% url 'dashboard:index' %}" class="px-6 py-2 bg-sky-700 text-white rounded hover:bg-sky-600 text-xl font-bold" style="padding: 20px 50px;">Dashboard</a>
  {% else %}
  <a href="{% url 'core:signup' %}" class="px-6 py-2 bg-sky-700 text-white rounded hover:bg-sky-600 text-xl font-bold" style="padding: 20px 50px;">Sign up</a>
  {% endif %}

</div>
<hr style="width: 60%; margin-left: 20%; margin-top: 20px; margin-bottom: 20px;">

{% endblock %}

core/templates/core/login.html
{% extends 'core/base.html' %}

{% block title %}Log in{% endblock %}

{% block content %}
    <div class="w-1/2 my-6 p-6 mx-auto bg-gray-100 rounded-xl">
        <h1 class="text-2xl text-center font-bold py-4">Log in</h1>

        <form method="post" action=".">
            {% csrf_token %}

            <div class="mb-3">
                <label class="inline-block mb-2" for="username">Username</label><br>
                {{ form.username }}<br>
            </div>

            <div class="mb-3">
                <label class="inline-block mb-2" for="username">Password</label><br>
                {{ form.password }}<br>
            </div>

            {% if form.errors or form.non_field_errors %}
                <div class="mb-3 p-6 bg-red-100 rounded-xl"
                    {% for field in form %}
                        {{ field.errors }}
                    {% endfor %}
                </div>

                {{ form.non_field_errors }}

            {% endif %}

            <br><button class="py-4 px-8 bg-sky-900 hover:bg-sky-800 text-white font-bold py-2 px-4 rounded" type="submit">Log in</button>

        </form>
    </div>

{% endblock %}

core/templates/core/signup.html
{% extends 'core/base.html' %}

{% block title %}Sign up{% endblock %}

{% block content %}
    <div class="w-1/2 my-6 p-6 mx-auto bg-gray-100 rounded-xl">
        <h1 class="text-2xl text-center font-bold py-4">Sign up</h1>

        <form method="post" action=".">
            {% csrf_token %}

            <div class="mb-3">
                <label class="inline-block mb-2" for="username">Username</label><br>
                {{ form.username }}<br>
            </div>

            <div class="mb-3">
                <label class="inline-block mb-2" for="username">Email</label><br>
                {{ form.email }}<br>
            </div>

            <div class="mb-3">
                <label class="inline-block mb-2" for="username">Password</label><br>
                {{ form.password1 }}<br>
            </div>

            <div class="mb-3">
                <label class="inline-block mb-2" for="username">Repeat password</label><br>
                {{ form.password2 }}<br>
            </div>

            {% if form.errors or form.non_field_errors %}
                <div class="mb-3 p-6 bg-red-100 rounded-xl"
                    {% for field in form %}
                        {{ field.errors }}
                    {% endfor %}
                </div>

                {{ form.non_field_errors }}

            {% endif %}

            <br><button class="py-4 px-8 bg-sky-900 hover:bg-sky-800 text-white font-bold py-2 px-4 rounded" type="submit">Sign up</button>

        </form>
        <hr style="width: 60%; margin-left: 20%; margin-top: 20px; margin-bottom: 5px; border: 1px solid gray;">
        <p class="text-center text-gray-500">Already have an account? <a href="{% url 'core:login' %}">Log in</a></p>
    </div>

{% endblock %}

core/templates/core/soon.html
{% extends 'core/base.html' %}

{% block title %}Coming soon{% endblock %}

{% block content %}
    <h1 class="text-center text-4xl font-bold mb-4 text-red-800">Coming soon</h1>
{% endblock %}