DjangoChickSim/urls.py
from django.conf.urls.static import static
from django.conf import settings

from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('core.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('buildings/', include('buildings.urls')),
    path('market/', include('market.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path

from .forms import LoginForm
from . import views


app_name = 'core'

urlpatterns = [
    path('', views.index, name='index'),
    path('signup/', views.signup, name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name='core/login.html', authentication_form=LoginForm), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('soon/', views.soon, name='soon'),
    path('live_data/', views.live_data, name='live_data'),
]

market/urls.py
from django.urls import path

from . import views

app_name = 'market'

urlpatterns = [
    path('', views.index, name='index'),
    path('buy_sell_eggs/', views.buy_sell_eggs, name='buy_sell_eggs'),
]

market/models.py
from django.db import models


class Shopping_item(models.Model):
    id = models.IntegerField(primary_key=True)
    name = models.CharField(max_length=50)
    description = models.TextField()
    costbuy = models.FloatField(default=0)
    costsell = models.FloatField(default=0)
    offset = models.FloatField(default=0.1)
    
    def __str__(self):
        return self.name

market/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from user.models import UserProfile, BuildingLevel
from django.contrib import messages
from market.models import Shopping_item

@login_required
def index(request):
    
    shoping_items = Shopping_item.objects.all()
    
    return render(request, 'market/index.html', {
        'shoping_items': shoping_items,
        })


@login_required
def buy_sell_eggs(request):
    if request.method == 'POST':
        user_profile = UserProfile.objects.get(user=request.user)
        item_name = request.POST.get('item_name')
        action = request.POST.get('action')
        
        item = getattr(user_profile, item_name)

        if action == 'buy':

            money = user_profile.money
            ammount = int(request.POST.get('eggs'))
            cost_buy = Shopping_item.objects.get(name=item_name).costbuy
            
            if money >= ammount:
                setattr(user_profile, item_name, item + ammount)
                user_profile.money -= ammount * cost_buy
                user_profile.save()
                messages.success(request, f'{ammount} {item_name} bought successfully')
            else:
                messages.error(request, f'Not enough money to buy {ammount} {item_name}')
        elif action == 'sell':
            ammount = int(request.POST.get('eggs'))
            cost_sell = Shopping_item.objects.get(name=item_name).costsell
            
            if item >= ammount:
                setattr(user_profile, item_name, item - ammount)
                user_profile.money += ammount * cost_sell
                user_profile.save()
                messages.success(request, f'{ammount} {item_name} sold successfully')
            else:
                messages.error(request, f'Not enough {item_name} to sell {ammount}')
        else:
            print(request.POST)
    return redirect('market:index')

market/templates/market/index.html
{% extends 'core/base.html' %}

{% block title %}Farmers Market{% endblock %}

{% block content %}
{% for msg in messages %}
{% if msg.tags == 'error' %}
<div class="px-6 py-4 mb-4 text-sm text-center bg-red-500 rounded-xl opacity-50 text-white-100 text-4xl font-bold">
    {{ msg }}
</div>
{% endif %}
{% if msg.tags == 'success' %}
<div class="px-6 py-4 mb-4 text-sm text-center bg-green-500 rounded-xl opacity-50 text-white-100 text-4xl font-bold">
    {{ msg }}
</div>
{% endif %}
{% endfor %}
<div class="mt-6 mb-6 px-6 py-12 bg-gray-100 rounded-xl">
    <h1 class="mb-6 text-4xl font-bold text-center text-sky-950">Marketplace</h1>
    <div class="flex flex-col items-center justify-center">
        <div class="grid grid-cols-3 gap-4">
            {% for item in shoping_items %}
            <div class="flex flex-col items-center justify-center border-2 rounded-xl shadow-xl">
                <p class="text-center text-2xl font-bold text-sky-950 mt-6">{{ item.name }}</p>
                <div class="border-2 mt-6 rounded-xl">
                    <div class="bg-green-200 rounded-xl mt-2 mb-4 ml-2 mr-2">
                        <p class="text-center border-2 border-green-200 rounded-xl"> Buy for: {{ item.costbuy }}$</p>
                    </div>
                    <div class="bg-red-200 rounded-xl mb-2 ml-2 mr-2">
                        <p class="text-center border-2 border-red-200 rounded-xl"> Sell for: {{ item.costsell}}$</p>
                    </div>
                </div>
                <form method="post" action="{% url 'market:buy_sell_eggs' %}">
                    {% csrf_token %}
                    <div class="flex flex-col items-center justify-center">
                        <input type="number" name="eggs" action="{% url 'market:buy_sell_eggs' %}" value="0" class="px-4 py-2 mt-4 mb-4 text-gray-700 bg-white border-2 border-gray-300 rounded-xl focus:outline-none focus:border-sky-950 w-1/2" placeholder="Eggs">
                        <input type="hidden" name="item_name" value="{{ item.name }}">
                        <button type="submit" name="action" class="px-4 mt-2 mb-2 py-2 text-white bg-green-950 rounded-xl hover:bg-green-800" value="buy">Buy {{ item.name }}</button>
                        <button type="submit" name="action" class="px-4 mb-2 mt-2 py-2 text-white bg-red-950 rounded-xl hover:bg-red-800" value="sell">Sell {{ item.name }}</button>
                    </div>
                </form>
            </div>

            {% endfor %}
</div>
</div>
{% endblock %}